"""empty message

Revision ID: 097d988ed1ec
Revises: 
Create Date: 2025-04-20 22:44:37.125551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097d988ed1ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costumer_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costumer_history', schema=None) as batch_op:
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###
