"""hehehe

Revision ID: 1fadcf284ae1
Revises:
Create Date: 2025-03-17 20:19:38.321029

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "1fadcf284ae1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("administrator", schema=None) as batch_op:
        batch_op.drop_column("admin_age")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("administrator", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("admin_age", mysql.INTEGER(), autoincrement=False, nullable=True)
        )

    # ### end Alembic commands ###
