"""update table name

Revision ID: 5a61e64c21a2
Revises: 1fadcf284ae1
Create Date: 2025-03-17 20:30:20.233736

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "5a61e64c21a2"
down_revision = "1fadcf284ae1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("table")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "table",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("table_name", mysql.VARCHAR(length=10), nullable=False),
        sa.Column(
            "isAvailable",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("current_costumer_name", mysql.VARCHAR(length=56), nullable=True),
        sa.Column(
            "current_costumer_id", mysql.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["current_costumer_id"], ["costumer.id"], name="table_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
