"""try

Revision ID: 7b83b13518dd
Revises: 5a61e64c21a2
Create Date: 2025-03-17 20:56:18.647633

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7b83b13518dd"
down_revision = "5a61e64c21a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("costumer", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("costumer_content", sa.String(length=126), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("costumer", schema=None) as batch_op:
        batch_op.drop_column("costumer_content")

    # ### end Alembic commands ###
