"""empty message

Revision ID: 8290e2ff50bb
Revises: e7efa9a0b908
Create Date: 2025-04-06 16:31:53.720333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8290e2ff50bb'
down_revision = 'e7efa9a0b908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costumer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costumer', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
