"""add

Revision ID: b7d7f85b8dae
Revises: 7b83b13518dd
Create Date: 2025-03-17 20:57:30.555681

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "b7d7f85b8dae"
down_revision = "7b83b13518dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("costumer", schema=None) as batch_op:
        batch_op.drop_column("costumer_content")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("costumer", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("costumer_content", mysql.VARCHAR(length=126), nullable=False)
        )

    # ### end Alembic commands ###
