"""empty message

Revision ID: c371c5e21de8
Revises: f78d88f4b1d4
Create Date: 2025-04-12 13:53:16.960709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c371c5e21de8'
down_revision = 'f78d88f4b1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.String(length=69), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_payments', schema=None) as batch_op:
        batch_op.drop_column('payment_type')

    # ### end Alembic commands ###
