"""empty message

Revision ID: f78d88f4b1d4
Revises: 4b57b7352a66
Create Date: 2025-04-12 12:42:05.759173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78d88f4b1d4'
down_revision = '4b57b7352a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orders', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_payments', schema=None) as batch_op:
        batch_op.drop_column('orders')

    # ### end Alembic commands ###
