"""empty message

Revision ID: fdf948b968f7
Revises: b7d7f85b8dae
Create Date: 2025-03-17 21:41:20.909611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf948b968f7'
down_revision = 'b7d7f85b8dae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_status', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['table_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_status', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
