"""empty message

Revision ID: febbc9f39625
Revises: b6c6b3f8621c
Create Date: 2025-03-22 13:21:12.805032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'febbc9f39625'
down_revision = 'b6c6b3f8621c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_request', schema=None) as batch_op:
        batch_op.drop_column('date_time')

    # ### end Alembic commands ###
